### PR TITLE
add logo for social card

### PR DESCRIPTION
**Pull request by rmorshea**
Add logo that works with social cards

## Checklist

Please update this checklist as you complete each item:

- [ ] Tests have been included for all bug fixes or added functionality.
- [ ] The `changelog.rst` has been updated with any significant changes.
- [ ] GitHub Issues which may be closed by this Pull Request have been linked.

### CODE REVIEW

**Comment by Archmonger** [comment]
I propose we play around with the ReactPy text font a bit.

Maybe [Roboto Bold](https://fonts.google.com/specimen/Roboto) or Segoe UI?

**Comment by rmorshea** [comment]
I'm not picky. The font I chose was literally the default sans font in Inkscape. Care to make that change?

**Comment by Archmonger** [comment]
I can work on it in a follow up PR

**Comment by rmorshea** [comment]
Speaking of bolding things though. Do you think the fact that there are snakes in the logo is clear at smaller scales? Obviously once it's small enough you can't tell. But when it's this big it seems like it might be too subtle:
image

**Comment by Archmonger** [comment]
Nope, not clear at all.

That's a common design issue with any intricate design. Same reason why [Python's snakes](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1280px-Python-logo-notext.svg.png) look so stupid. Making geometry simplified and oversized is the only way to retain visual clarity a small sizes.

**Comment by rmorshea** [comment]
Yup. I think I'm at the limits of my creative abilities here though. Probably need to pay someone if we want something better. Who knows, maybe it's too difficult to make work, but I'm kind of attached to the concept at least.

**Comment by Archmonger** [comment]
I agree we should stick with the concept, it's the only thing that logically conveys our project. I'm okay with pitching in for a graphics artist.

**Pull request merged**
