### PR TITLE
Better Async Effects

### LINKED ISSUE #956: Better Async Effect Cleanup
### Current Situation

Presently, the "cleanup" behavior for async effects is that they are cancelled before the next effect takes place or the component is unmounted. While this behavior may be desirable in many cases, it does not give the user the ability to gracefully deal with cleanup logic in the way one can with a sync event.

For example, consider a long running async effect:

```python
@use_effect
async def long_running_task():
    while True:
        await something()
        await something_else()
```

The problem with this current behavior is that handling the cancellation is messy. You could do the following:

```python
@use_effect
async def long_running_task():
    try:
        while True:
            await something()
            await something_else()
    finally:
        ...  # cleanup logic here
```

However, this may lead to some confusing behavior since it's not possible to know whether `something()` or `something_else()` will receive the cancellation. You might have to do a lot of extra work to figure out what state your program was left in after the cancellation.

### Proposed Actions

Thankfully the above only impacts async effects. With a synchronous event, you would be able to handle async task cleanup using something like the following:

```python
@use_effect
def start_long_running_task():
    interupt = Event()
    asyncio.create_task(long_running_task(interupt))
    return cleanup.set

async def long_running_task(interrupt):
    while not interupt.is_set():
        await something()
        await something_else()
    ...  # cleanup logic here
```

Given this, our proposed solution to the problem is to allow async effects to accept a similar interupt `asyncio.Event`:

```python
@use_effect
async def long_running_task(interrupt):
    while not interupt.is_set():
        await something()
        await something_else()
    ...  # cleanup logic here
```

### PR DESCRIPTION
**Pull request by rmorshea**
<sub>By submitting this pull request you agree that all contributions to this project are made under the MIT license.</sub>

## Issues

Closes: #956

## Solution

Async effects now accept a "stop" `Event` that is set when an effect needs to be re-run or a component is unmounting. The next effect will only run when the last effect has exited.

```python
@use_effect
async def my_effect(stop):
    ... # do work
    await stop.wait()
    ... # do cleanup
```

Implementing this same behavior using sync effects is quite challenging:

```python
import threading, asyncio
from reactpy import use_effect, use_ref


def use_async_effect(func):
    thread = use_ref(None)

    @use_effect
    def my_effect():
        if thread.current is not None:
            # wait for last effect to complete
            thread.current.join()

        loop = stop = None
        started = threading.Event()

        def thread_target():
            async def wrapper():
                nonlocal loop, stop
                loop = asyncio.get_running_loop()
                stop = asyncio.Event()
                started.set()
                await func(stop)

            asyncio.run(wrapper())

        # start effect
        thread.current = threading.Thread(target=thread_target, daemon=True)
        thread.current.start()
        started.wait()

        # register stop callback
        return lambda: loop.call_soon_threadsafe(stop.set)
```

To achieve this without requiring an implementation similar to the above, we've asyncified the internals of `Layout`. This has the side-effect of allowing other things to happen while the `Layout` is rendering (e.g. receive events, or allowing the server to respond to other requests). This potentially comes at the cost of rendering speed. For example, if a user is spamming the server with events renders may be interrupted in order to respond to them.

## Checklist

- [ ] Tests have been included for all bug fixes or added functionality.
- [ ] The `changelog.rst` has been updated with any significant changes.

### CODE REVIEW

**Comment by Archmonger** [comment]
This interface should be relatively similar to the [`use_messenger` hook we designed](https://github.com/reactive-python/reactpy/pull/1084#issuecomment-1624765310).

Notes
- We should timeout the effect if it takes too long to teardown
- A 2 second timeout is a good default for most situations.
- Needs a `teardown: Coroutine` parameter in the hook

```python
import asyncio
from reactpy import component, use_effect

@component
def example():
    async def teardown():
       ...

    @use_effect(timeout=2, teardown=teardown)
    async def example_effect(cancel: asyncio.Event):
        while True:
            await something("my-message-type")
            ...

            if cancel.is_set():
                break
```

**Comment by rmorshea** [comment]
> Needs a teardown: Coroutine parameter in the hook

I think this is a slight simplification - teardown should just happen after the stop event is triggered.

```python
@use_effect
async def effect(stop):
    # do effect
    await stop.wait()
    # cleanup
```

> We should timeout the effect if it takes too long to teardown

I thought about this for a bit and realized that a simple `timeout` parameter is ambiguous - does it apply to the effect creation or cleanup. I'd rather not complicate it with more parameters. Adding a timeout is also quite easy:

```python
await asyncio.wait_for(task(), timeout...)
```

**Comment by Archmonger** [comment]
> teardown should just happen after the stop event is triggered.

This can't always occur though. For example, in the case of the user closing their browser window. We need a timeout to cover edge cases like this.

> a simple timeout parameter is ambiguous

We can call it `exit_timeout`, `cancel_timeout`, or `stop_timeout`

> Adding a timeout is also quite easy:
> `await asyncio.wait_for(task(), timeout...)`

What you proposed isn't equivalent to a `stop_timeout`.

**Comment by rmorshea** [comment]
Both comments seem to address the fact that we might want to enforce a timeout when a connection is closed. That seems reasonable, but in that case, it seems better to introduce that timeout here when a `Layout` is exiting:  https://github.com/reactive-python/reactpy/blob/c311345eacea2e22753adebaf2191b516ddee68a/src/py/reactpy/reactpy/core/layout.py#L75

Though, even without this, the user could enforce a "stop timeout" themselves if they wanted:

```python
await wait_for(create_effect(), timeout=...)  # creation timeout
await stop.wait()
await wait_for(cleanup_effect(), timeout=...)  # cleanup timeout
```

**Comment by rmorshea** [comment]
So thinking through our interface some more I'm realizing that:

```python
@use_effect
async def my_effect(stop):
    task = asyncio.create_task(do_something())
    await stop.wait()
    task.cancel()
    await finalize_it()
```

Is not correct since simply cancelling a task does not mean that it will have exited by the time `finalize_effect` starts running. The correct implementation would actually be:

```python
@use_effect
async def my_effect(stop):
    task = asyncio.create_task(do_something())
    await stop.wait()
    task.cancel()
    try:
        await task
    except asyncio.CancelledError:
        pass
    await finalize_it()
```

This is far too complicated for users to understand.

As such, I've done some thinking and realized that in 3.11 `asyncio` got some interesting new features that would allow the above to be implemented with this instead:

```python
@use_effect
async def my_effect(effect):
    async with effect:
        await do_something()
    await finalize_it()
```

The behavior is that awaitables within the `body` will be cancelled if they have not completed by the time the effect needs to stop. The `body` will also pause until the effect needs to be stopped, thus allowing you to perform finalization after exiting the body. If you want to implement a "fire and forget" effect, then you simply ignore the `body` and do not enter it.

The implementation of the `effect` context manager would look something like:

```python
class AsyncEffect:

    _task: asyncio.Task | None = None

    def __init__(self) -> None:
        self._stop = asyncio.Event()
        self._cancel_count = 0

    def stop(self) -> None:
        if self._task is not None:
            self._cancel_task()
        self._stop.set()

    async def __aenter__(self) -> None:
        self._task = asyncio.current_task()
        self._cancel_count = self._task.cancelling()
        if self._stop.is_set():
            self._cancel_task()
        return None

    async def __aexit__(self, exc_type: type[BaseException], *exc: Any) -> Any:
        if exc_type is not asyncio.CancelledError:
            # propagate non-cancellation exceptions
            return None

        if self._task.cancelling() > self._cancel_count:
            # Task has been cancelled by something else - propagate it
            return None

        await self._stop.wait()
        return True

    def _cancel_task(self) -> None:
        assert self._task is not None
        self._task.cancel()
        self._cancel_count += 1
```

**Comment by Archmonger** [comment]
Is there any way for us to use Python 3.11 asyncio features in older versions?

I'm pretty sure the answer is no, and if so what do we want to do in the interim while we wait for 3.11 to become our minimum version?

**Comment by rmorshea** [comment]
I'll have to play around with whether this can be achieved with `anyio`. It may be possible.

**Comment by Archmonger** [comment]
If we're going to introduce async specific `use_effect` parameters, we might want to separate async effects into their own hook.

Such as `use_async_effect`.

**Comment by rmorshea** [comment]
~@Archmonger I'm encountering some [issues with lxml during installation](https://github.com/reactive-python/reactpy/actions/runs/6916649844/job/18816942704?pr=1093). I fixed a similar issue by installing `setuptools` but that [doesn't seem to be helping](https://github.com/reactive-python/reactpy/blob/0319e4db7dd3cbb0d52bd02c6dc4c68cf385c097/src/py/reactpy/pyproject.toml#L38).~

Limiting the default python version to 3.11 seems to have fixed it.

**Comment by rmorshea** [comment]
I'm going to close this and break up the changes into two parts:

1. Concurrent renders
2. Async effects.

**Pull request closed without merging**
