### PR TITLE
Move JS directory inside reactpy to fix broken source distributions

### LINKED ISSUE #1184: NotADirectoryError when installing from source distribution
### Discussed in https://github.com/reactive-python/reactpy/discussions/1180

<div type='discussions-op-text'>

<sup>Originally posted by **thegamecracks** January  3, 2024</sup>
When attempting to install the package specifically using its source distribution rather than the built wheels, the following error occurs:

```py
>pip install reactpy --no-binary reactpy 
Collecting reactpy
  Using cached reactpy-1.0.2.tar.gz (123 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "..\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "..\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Temp\pip-build-env-qtfs6sj6\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Temp\pip-build-env-qtfs6sj6\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "..\AppData\Local\Temp\pip-build-env-qtfs6sj6\overlay\Lib\site-packages\hatch_build_scripts\plugin.py", line 51, in initialize
          run(cmd, cwd=str(work_dir), check=True, shell=True)  # noqa: S602
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "..\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      NotADirectoryError: [WinError 267] The directory name is invalid
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

After some debugging, it appears that hatch is trying to build the JavaScript client and assumes `src/js/` is present, but in the source distribution that directory is missing. Here is the build configuration in question:

https://github.com/reactive-python/reactpy/blob/3a3ad3f706477642133190c08bbe1e43a991bfa3/src/py/reactpy/pyproject.toml#L127-L136

Right now, both the sdist and wheels uploaded on PyPI contain the `reactpy/_static/` files generated by `npm run build` ([inspector](https://inspector.pypi.io/project/reactpy/1.0.2/)), but hatch is configured to build the client even when the source distribution already has the output files. This isn't a major issue since reactpy's wheels aren't dependent on system architecture, but it would be nice to have this part of the build process fixed (or at least documented).

The ideal solution would be to include the JS client's source code in the sdist and only build it when installing from source / generating the wheel. I thought of suggesting this:

```diff
+ [tool.hatch.build.targets.sdist.force-include]
+ "../../js" = "js"
+ 
+ [tool.hatch.build.targets.wheel.force-include]
+ "reactpy/_static" = "reactpy/_static"  # bypass .gitignore

- [[tool.hatch.build.hooks.build-scripts.scripts]]
- work_dir = "../../js"
+ [[tool.hatch.build.targets.wheel.hooks.build-scripts.scripts]]
+ work_dir = "js"
```

However it breaks installing from source (`pip install src/py/reactpy`) as pip skips building the sdist and therefore won't copy `js/` to the correct place. I also don't know if there's an alternative to [`force-include`](https://hatch.pypa.io/latest/config/build/#forced-inclusion) which can map paths outside of the project root while respecting .gitignore. Absent that, it would be easy to accidentally pollute the sdist with `node_modules`.

In theory a symbolic link to `src/js/` could remedy this along with slightly different changes to pyproject.toml, specifically the use of `only-include`:

<a id="include-js-in-sdist" />

```diff
+ [tool.hatch.build.targets.sdist]
+ only-include = ["js", "reactpy"]
+ 
+ [tool.hatch.build.targets.wheel.force-include]
+ "reactpy/_static" = "reactpy/_static"  # bypass .gitignore

- [[tool.hatch.build.hooks.build-scripts.scripts]]
- work_dir = "../../js"
+ [[tool.hatch.build.targets.wheel.hooks.build-scripts.scripts]]
+ work_dir = "js"
```

But while it works when generating the sdist / building from sdist ([`python -m build`](https://build.pypa.io/en/stable/)), the `npm run build` command fails when installing from source or building the wheel from source (`hatch build`/`python -m build --wheel`):

<details>

```py
(.venv) ..\reactpy\src\py\reactpy>pip install .
Processing ..\reactpy\src\py\reactpy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [74 lines of output]

      added 249 packages, and audited 258 packages in 5s

      89 packages are looking for funding
        run `npm fund` for details

      3 moderate severity vulnerabilities

      To address all issues, run:
        npm audit fix

      Run `npm audit` for details.

      > build
      > npm --workspaces run build


      > event-to-object@0.1.2 build
      > tsc -b


      > @reactpy/client@0.3.1 build
      > tsc -b

      src/reactpy-vdom.tsx(3,28): error TS2307: Cannot find module 'event-to-object' or its corresponding type declarations.
      npm ERR! Lifecycle script `build` failed with error:
      npm ERR! Error: command failed
      npm ERR!   in workspace: @reactpy/client@0.3.1
      npm ERR!   at location: ..\reactpy\src\py\reactpy\js\packages\@reactpy\client

      > build
      > vite build

      vite v3.2.7 building for production...
      transforming...
      âœ“ 9 modules transformed.
      [vite]: Rollup failed to resolve import "event-to-object" from "../../../../js/app/node_modules/@reactpy/client/dist/reactpy-vdom.js".
      This is most likely unintended because it can break your application at runtime.
      If you do want to externalize this module explicitly add it to
      `build.rollupOptions.external`
      error during build:
      Error: [vite]: Rollup failed to resolve import "event-to-object" from "../../../../js/app/node_modules/@reactpy/client/dist/reactpy-vdom.js".
      This is most likely unintended because it can break your application at runtime.
      If you do want to externalize this module explicitly add it to
      `build.rollupOptions.external`
          at onRollupWarning (file:///../reactpy/src/js/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45909:19)
          at onwarn (file:///../reactpy/src/js/node_modules/vite/dist/node/chunks/dep-2faf2534.js:45680:13)     
          at Object.onwarn (file:///../reactpy/src/js/node_modules/rollup/dist/es/shared/rollup.js:23263:13)    
          at ModuleLoader.handleResolveId (file:///../reactpy/src/js/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
          at file:///../reactpy/src/js/node_modules/rollup/dist/es/shared/rollup.js:22119:26
      npm ERR! Lifecycle script `build` failed with error:
      npm ERR! Error: command failed
      npm ERR!   in workspace: undefined
      npm ERR!   at location: ..\reactpy\src\py\reactpy\js\app
      Traceback (most recent call last):
        File "..\reactpy\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "..\reactpy\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\reactpy\.venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Temp\pip-build-env-4ebt3ux8\overlay\Lib\site-packages\hatchling\build.py", line 58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Temp\pip-build-env-4ebt3ux8\overlay\Lib\site-packages\hatchling\builders\plugin\interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "..\AppData\Local\Temp\pip-build-env-4ebt3ux8\overlay\Lib\site-packages\hatch_build_scripts\plugin.py", line 51, in initialize
          run(cmd, cwd=str(work_dir), check=True, shell=True)  # noqa: S602
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "..\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'npm run build' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

</details>

FWIW, in an unrelated package, [sardine-web](https://github.com/sardine-system/sardine-web/tree/v1.1.0/), I structured it so the JS client's source code was inside the package itself, but [setup.py](https://github.com/sardine-system/sardine-web/blob/v1.1.0/setup.py#L56-L67) would build the client and remove the source code afterwards, leaving only the source code in the sdist and its compiled result in the wheel. In hindsight, it probably would have been easier had I left the client source code outside of the package and only included it in the sdist via MANIFEST.in. Given hatch's own mechanisms for controlling distributions, plus the convenience of `hatch-build-scripts`, it might be easier to move `src/js/` beside the `src/py/reactpy/reactpy/` package and follow the [previous suggestion](#include-js-in-sdist) to pyproject.toml, rather than try to find a workaround with the current layout.</div>

### PR DESCRIPTION
**Pull request by thegamecracks**
## Issues

https://github.com/reactive-python/reactpy/discussions/1180

## Solution

This PR moves the JS directory inside reactpy and tweaks the build process so hatch can produce source distributions that contain the JS client's source code necessary for end users to build the package.
Due to this being a major change in the project structure, developers will need to adapt their workflows to the new location of `js/`.

## Checklist

- [ ] Tests have been included for all bug fixes or added functionality.
- [x] The `changelog.rst` has been updated with any significant changes.

### CODE REVIEW

**Comment by Archmonger** [comment]
Your original comment mentions that a symlink has issues, but could a hard link work instead of moving the source folder?

**Comment by thegamecracks** [comment]
> Your original comment mentions that a symlink has issues, but could a hard link work instead of moving the source folder?

@Archmonger As far as I know, most operating systems don't support hard linking directories. You could hard link all the individual source files instead, but it seems that Git doesn't distinguish hard links from normal files so they can't be preserved in version control.

**Comment by Archmonger** [comment]
I'd say we hard link all files recursively, and then have a `.gitignore` for the entire hardlinked directory (`src/py/reactpy/js/*`).

Burying the JavaScript source within the Python source feels awkward to me for something that's fundamentally just a build tools problem.

**Comment by thegamecracks** [comment]
That has similar issues to `js/` being `force-include`'d since it appears hatch doesn't have a clear way to only affect the sdist and source installations while skipping wheels being built from sdist. Perhaps a single hatch_build.py could be written with some reliable way to detect this and copy accordingly?

As for avoiding intermixed Python and JavaScript source directories, I think the difficulties in configuring the build system stems from it not sufficiently supporting file structures that go past the root of pyproject.toml, which is what determines the sdist archive root. Given that reactpy is the main package of the project, an alternative to moving the sources around could be placing `reactpy/pyproject.toml` at the repository root so the build system has an easier time including both source directories.

**Comment by Archmonger** [comment]
I've discussed with @rmorshea in the past of removing Hatch from this repo's workflow. There wasn't any issues with the old `setuptools` installation method, and the [reason we switched](https://github.com/reactive-python/reactpy/pull/1002) to hatch was the concept of a monorepo.

But the monorepo never happened, so this feels like added complexity and bugs for little gain.

**Comment by rmorshea** [comment]
Is there any downside to just not shipping an sdist, or at least delaying this change? I can work on switching back to a `setuptools`-based workflow but it'll just be fairly tedious. Some of the scripts are dependent on the current repo structure so unfortunately it won't be as simple as just moving this directory around.

**Comment by thegamecracks** [comment]
That's a fair approach too. Based on the [packaging guide](https://packaging.python.org/en/latest/flow/#the-source-distribution-sdist), the risks of not publishing an sdist would be:

1. Preventing users from building reactpy for their own system
2. Potentially losing the project source code if the original repository is lost

The first point matters less to reactpy since it has a pure-python wheel, but if some future change makes the build process dependent on system architecture, it becomes extra important for reactpy (or possibly a third-party) to provide wheels for every system architecture that its users might have, perhaps with a tool like [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/). The second point depends on how easily users can access the repository, which I think is probably going to be fine for the forseeable future.

Another way to fix the sdist could be to update tasks.py so it hard links the files before installation, and also include some "relink" command to repeat the same hard linking before proceeding with building/publishing, combining the pyproject.toml changes and @Archmonger's suggestion together. The limitations change from having the source code intermixed in version control to a more complicated, but still automated build process, which seems like a better tradeoff in regards to the monorepo structure. Either way, I don't disagree with dropping the sdist or going back to setuptools.

**Comment by kumaraguru1735** [comment]
@thegamecracks , I already told they will not accept others PR, Just a deadly project this is ...

**Comment by Archmonger** [comment]
@kumaraguru1735 right now Ryan is the only one with permission to approve PRs for this repo, but he hasn't had time to do any OSS.

It's okay to criticize things moving slow, but the toxicity isn't appreciated.

**Comment by kumaraguru1735** [comment]
@Archmonger , why not you don't have permission for PR ? You are team of Reactpy wright ?

**Comment by kumaraguru1735** [comment]
@Archmonger , if he fails to give permission, I think you are not part of the game! I hope you will create seperate repo and put on own ideas and Maintain it

**Comment by rmorshea** [comment]
@Archmonger has been granted admin privileges now.

**Comment by rmorshea** [comment]
I'm working on a solution to this that won't involve moving the directory. As per @thegamecracks's suggestion just linking the JS directory and including it as an sdist-only artifact should be sufficient.

**Comment by Archmonger** [comment]
@rmorshea I think you might also have to set me as an organization owner. I can't change workflow settings, which prevents me from changing required workflows.

**Comment by Archmonger** [comment]
Closing this since Ryan is pushing for #1191

**Pull request closed without merging**
