### PR TITLE
Fix pylint issues

### PR DESCRIPTION
**Pull request by Archmonger**
See [this link](https://github.com/idom-team/idom/pull/919#issuecomment-1441081230) for details.

## Checklist

Please update this checklist as you complete each item:

- [x] Tests have been included for all bug fixes or added functionality.
- [x] The `changelog.rst` has been updated with any significant changes.
- [x] GitHub Issues which may be closed by this Pull Request have been linked.

### CODE REVIEW

**Comment by rmorshea** [comment]
It looks like there may actually be a way to work around this: https://github.com/PyCQA/pylint/pull/2926

```
[tool.pylint.typecheck]
signature-mutators = ["idom.core.vdom.custom_vdom_constructor"]
```

**Comment by Archmonger** [comment]
This would for internally for our own test suite, but our `pyproject.toml` isn't distributed within our pypi package. We could add it (or a `.pylintrc`) to our distribution, but that's a bit weird.

**Comment by rmorshea** [comment]
Can you add a comment about why we do this with a link to the GitHub issue?

**Comment by rmorshea** [comment]
I'm contemplating making a contribution that would allow us to achieve this with a comment. It seems kind of annoying to have to dirty up our code because of this.

**Comment by Archmonger** [comment]
I don't know if that's technologically possible within PyLint's stack. It likely would require us to go down the rabbit hole of fixing https://github.com/PyCQA/pylint/issues/5784

**Comment by rmorshea** [comment]
I think I did it: https://github.com/PyCQA/pylint/pull/8332

**Review by rmorshea — APPROVED** [review]

**Pull request merged**
