### PR TITLE
Fix flask backend mimetype for modules

### PR DESCRIPTION
**Pull request by elro444**
<sub>By submitting this pull request you agree that all contributions to this project are made under the MIT license.</sub>

## Issues

When running reactpy with Flask backend, `web.module_from_template` resulted an error (in the browser) about wrong mimetype. In example:
```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:8000/_reactpy/modules/__from_template__/@material-ui/core@4.12.4.4.js
```

## Solution

Explicitly add the mimetype when using `send_file`

## Checklist

- [ ] Tests have been included for all bug fixes or added functionality.
- [x] The `changelog.rst` has been updated with any significant changes.

### CODE REVIEW

**Comment by rmorshea** [comment]
I think we can do this, but is this possibly related to [this sort of issue](https://github.com/reactive-python/reactpy/discussions/1073)?

**Comment by elro444** [comment]
Possibly, but doesn't seem to be exactly the same.  
In any case, I just lookd at reactpy's implementation for the sanic backend, and saw that we do indeed pass there the `text/javascript` mimetype.

**Comment by elro444** [comment]
Umm, seems like the lint checks are broken?  
Is it supposed to fail on files that i havened modified?

**Comment by rmorshea** [comment]
No. I'll put up a fix for that shortly.

**Comment by elro444** [comment]
Hey @rmorshea any updates on this issue?

**Review by rmorshea — APPROVED** [review]

**Pull request merged**
